version: "3"

services:
  shadowsocks-client:
    image: $SHADOWSOCKS_VERSION
    command: ss-local -s $SERVER_ADDR -p $SERVER_PORT -k $PASSWORD -m $METHOD -l 1080 -u
    container_name: $CONTAINER_NAME
    environment:
      - SERVER_ADDR=$SERVER_ADDR
      - SERVER_PORT=$SERVER_PORT
      - PASSWORD=$PASSWORD
      - METHOD=$METHOD
    ports:
      - "$CLIENT_PORT:1080"
    networks:
      network:
        ipv4_address: $LOCAL_IP

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: $NETWK_ADDR
          gateway: $NETWK_GATE